### ISSUE TITLE
Introduce yourself...

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e28-spring21#1]
Hi everyone - 

To kick off the semester, let's take a moment to get to know a little bit about each other...

**Tell us what brought you to this course and any other details you care to share.**

A little bit about myself - I'm a web programmer and educator, living in Arlington, MA. 

In addition to this course, I also teach [DGMD E-2](https://hesweb.dev/e2) and [CSCI E-15](https://hesweb.dev/e15). I've also worked with students completing their capstones in the DGMD program.

In the past, I've taught at Wellesley, UPenn, and UMiami. When working in industry I was the head developer for an online e-commerce store. More about my background here: [susanbuck.net](https://susanbuck.net)

All in all, I love creating things with code and teaching others how to do the same.

Looking forward to getting to know you all!

**Comment by sgreene** [comment]
Hi everyone,
My name is Simeon Greene. I've been a software engineer for over 20 years. I primarily code in Java and mostly work on server-side components. I took this course because I really want to improve my UI and front-end coding skills. I'm quite familiar with Javascript but my skills in that language have lagged behind for quite some time now. So I'm looking forward to upgrading them with this course.
For hobbies I enjoy running, mountain biking and of course coding! Feel free to connect with me on [LinkedIn](https://www.linkedin.com/in/simeongreene/) .

Looking forward to working with all of you in this course!

**Comment by acomjean** [comment]
Hello,

My name is Aram Comjean.  I've been working software for about 20 years.  I've been doing web type development for the past 10.   Currently at Harvard .    [https://fgr.hms.harvard.edu/toolsI](https://fgr.hms.harvard.edu/tools).  We write a lot of php and python, maintain Java and Perl.  

I volunteer with the [Somerville Open Studios]( https://www.somervilleopenstudios.org/) webiste

Looking to learn how to use these new Javascript front end frameworks.  I like  visualizing data.  

Hobbies include software, biking and art.  

Looking forward to this.

**Comment by dan-harnden** [comment]
Hello All,

My name is Dan Harnden I've been a Network System Administrator and Instructor in and out of uniform for roughly 18 years with the Department of Defense. 

I live in Pennsylvania, but my roots go way back to the early days of Massachusetts. We're the founding fathers of Wilmington, MA. So, I was kind of excited to find an opportunity to have a Harvard experience and work towards my ALM.


I have an AAS in Information Technology, and a BS in Network Engineering. I'm working on being accepted into the Software Engineering Program. I have programmed in many languages for various reasons, but I'm not as experienced as some of you mentioned above. 


I like playing with any kind of technology, I like seeing what makes it tick, and how I might be able to incorporate it into something better. I guess that's my hobby if you can call it one.


Is there a place we are supposed to be in lecture at the moment? I'm quite new to GitHub, as in 15 minutes new to it...

**Comment by susanBuck** [comment]
Hi @dan-harnden - There's no synchronous aspect of this course, so no place you need to be for lecture.

The Week 1 material has been posted at https://hesweb.dev/e28/week/1.

In case you didn't receive it, here's the welcome email I sent last week to registered students that elaborates on this:

![image](https://user-images.githubusercontent.com/237711/105932190-8a431380-601a-11eb-8ebd-f5a1777472a8.png)

Let me know if you have any questions about this. :)

**Comment by keamarg** [comment]
Hi everyone

I am Martin, hailing from Copenhagen Denmark. Great meeting you all through these presentations!

I work at a Danish academy of applied science as a development consultant, focusing on projects involving education, study competences etc. (both on concept and development side). I have a mixed educational background with main focus on humanities from my bachelors, but also some tech from my design/analysis oriented masters in Media technology and games.

Before my current job, I worked six years for a game company developing computer games as a UX and usability specialist, and after that I taught religious studies (anthropological, non-confessional version) and Informatics (two separate classes;)) in highschool for four years. I took a few programming classes in Java, and I am self-taught in HTML/CSS. Last semester, I took the CSCI-E3 course in javascript. So definitely not as adept as some of you guys in the ways of programming.

I am hoping that this class will give me some good insights on using Vue.js for small projects. Oh, and I am pursuing the graduate certificate in "Front end development".

Looking very much forward to learning Vue.js, and hopefully getting to know each other a bit.

**Comment by bryonjustice** [comment]
Hello everyone,
My name is Bryon Justice.  I have worked in IT for many years in various roles.  I currently lead an organization responsible for test engineering of my employer's enterprise applications.  I am nearing the completion of my requirements to fulfill the ALM in Information Management Systems and have been looking forward to an opportunity to enjoy some frontend development and learn the latest javascript frameworks/vue.js.

Looking forward to the semester ahead and the opportunity to learn with all of you.

**Comment by kerynegan** [comment]
Hello everyone!

My name is Keryn Egan, and I am a degree candidate in the digital media design ALM program. After this term, I will just have the two pre/capstone courses remaining. I have the beginnings of a plan to build a JavaScript/Node.js application for my capstone project, so I am especially excited to be here, both to learn more about VueJS and evaluate the ways I might utilize it in my project, and more generally to just have the opportunity to further practice my skills before I go off on my own.

Outside of the master's program, I work full-time at Harvard as part of the registrar's office at the Extension School, with a focus on the catalog, course scheduling, and --in pre-covid times-- classroom assignments. In my spare time, I love to work on both illustration and stationery design projects, and I hope to launch an online shop by mid-year. 

Looking forward to the class and seeing where we all are by the end of the term!

**Comment by misskimdo** [comment]
Hi, all! 

My name is Kim Do. I have worked in graphic/web design and marketing for the past 13 years. I quit my FT job in marketing to pursue an ALM in Digital Media Design (halfway there!) I took CSCI S-3 this past summer and my favorite part was learning about Vue.js so this class really caught my attention. 

Since I come from a design background, coding is not my forte - but that's why I'm here.

I live in Austin, TX and will be moving to Tokyo in the summer. I have too many hobbies and since I'm more of a visual person, you can see one of them [here](https://kimdotron.com/eats/).

Excited and nervous about all to come!

**Comment by seanbollin** [comment]
Hi my name is Sean Bollin.

I live in Bellevue, WA. I have been working as a professional Software Engineer for several years - mostly focused on the back-end these days.

I took this course because I wanted a refresher on client-side tech (Javascript/HTML/CSS) so it can help me in working on a game I'm developing!

**Comment by hhuang56** [comment]
Hi everyone! My name is Haley. I currently live in the Capitol Hill district of Washington D.C. working for IBM as a senior consultant focused primarily in front end/full stack application development. I'm taking this course as part of my journey towards a Master's in Software Engineering, but specifically because I've had some experience with React and Angular but no exposure to Vue.

Outside of work and school, I enjoy working on home renovation projects and playing video games with my husband. I am also the proud mother of two beautiful korat cats named Ada and Escher. Nice to meet you all! :)

**Comment by agt25** [comment]
Hello, everyone!

It’s so nice to meet you all! I’m an undergrad concentrating in computer science. And I’m so amazed by the diversity of HES! It’s been a running theme, every term, that I walk away speechless after reading my peer’s introductions. Frankly, I also grow a bit nervous as I’m nowhere near as accomplished and don’t have much career experience. 

Nevertheless, I’m so excited for e28 and cannot wait to learn and grow! Good luck this term, everyone!

**Comment by jaredmimms** [comment]
Hello. 

My name is Jared Mimms. I live in San Diego, CA. I currently work in genomics consulting. I am an ALM candidate in Extension Studies field: Digital Media Design (accepted student). I am studying to become a full stack developer. 

I'm excited to learn a new frontend website development framework. I have experience with AngularJS and Node.js. I want to become more well rounded in web development frameworks. 

Looking forward to meeting everyone!

**Comment by trevjburns** [comment]
Hey everyone,

My name is Trevor. I live in Maryland and I work as a full-stack software developer. I began my career in software as a "self-taught" developer five years ago, and now I'm pursuing an ALB in Computer Science to fill in knowledge gaps and expand my career opportunities. 

I look forward to learning this new framework with you all!

**Comment by oms210** [comment]
Hi everyone, 
I am Omarr Syed from Chicago, IL. I am a full-time software engineer working for Experian for the past 10 years. I have a master's degree from the Illinois Institute of Technology in Information Technology and Management. I mostly have been a .NET guy almost all my career but have worked on a number of other programming languages/frameworks as well, java, angular, knockout, objective-C (who remembers that?).. to name a few. Played with the android studio as well in the past but I have been out of touch with mobile development for quite some time now. 
I am a dad of three kids, 8-year-old and 5-year-old boys and a 3-year-old princess. So, it was a difficult decision to start on my certificate but hopefully, 2021 would ease everyone back into their normal routine (read: back to school). I also love cars, fast cars. Own a '19 Mustang GT which I call my 4th kid :-).

I am looking to getting back into learning new technologies and this course is the first step in that direction. 
Feel free to reach out to me if you like to discuss anything.
Good luck to everyone!

**Comment by richiecarey** [comment]
Hi all .. I'm Richie, a web developer from Cape Cod, Massachusetts. I'm taking this course as a first step toward the Back-End Web Developer certificate. I had originally planned to take this class last fall but, due to work conflicts, I opted for this semester instead. At my day job I work primarily with the Drupal 8 content management but our team also maintains a custom Vue.js app search application that will need modifications in the months ahead. Looking forward to learning Vue.js from the ground up and being a part of this class with you all!

**Comment by nverno** [comment]
Hi all,
I'm Noah, trying to transition to a software/web dev role. I've just finished a dev bootcamp, was previously in research, and am finishing up the software engineering masters at HES.  Current in LA, but usually in Boston.  Excited to learn Vue and build some apps.

**Comment by katz2row** [comment]
Hi! My name is Charity Katz. I live in SoCal and work as a Technical Curriculum Developer for a software company. I've been in and out of software companies for the last 14 years or so but always focused on training and development. My current company uses a lot of JavaScript for more advanced elements within the software. So I have been focused on classes that might help me expand the elearning options by focusing on the advanced elements of our system. I am also working on my Web Technologies Certification through Harvard Extension.

Besides that, I am a single parent to an amazing but dramatic toddler who thinks she's a teenager. With COVID, I had to pull her from school. So managing her, my work, and school is a difficult balancing act, but ultimately, the payoff is well worth it. If that's not enough, I'm also mom to two, senior dogs who like to drive me nuts. At least they are cute - ok... one is cute, and the other is just ugly and mean, but I still love her.

Here's to a good semester.

**Comment by EkaterinaMolchanova** [comment]
Hi everyone, 
My name is Ekaterina Molchanova. I live in Brookline, MA. My long-term goal is earning ALM in Digital Media Design, and this course is a step there. 
After spending about 15 years in finance and photography, I've decided to try web development. I like the idea of mixing the artistic side of digital design and the structure and logic of coding. 
I have no coding experience except for two courses I had in the fall semester but love it a lot so far! 
I'm looking forward to learning with and from all of you!

**Comment by susanBuck** [comment]
Thanks everyone for taking the time to introduce yourselves. Always enjoy reading about everyone's varied backgrounds and experience!
