### ISSUE TITLE
Inline Javascript

### ISSUE THREAD

**Issue by dan-harnden** [susanBuck/e28-spring21#14]
This is a general confusion question. Several times (unless I heard or saw it incorrectly) it was mentioned that Javascript in this class was fine to use either internally, or externally, but not inline.

I'm sorry, but I don't understand the actual difference between internal and inline. Could someone explain, please?

V/R
Dan

**Comment by bryonjustice** [comment]
HTML, CSS, JS are complementary technologies in the development of web applications. HTML provides the structure of content, CSS the presentation, and JS the behavior/interactivity. Generally, a best practice is to follow the design principle of **separation of concerns (SoC)**.  

In organizing your code the best practice is to separate the HTML, CSS and JS code into distinct source files to align with the principle of SoC.  In some of the lecture instruction and requirements on some earlier homework assignments the professor has not mandated following this practice.  The intention in these examples was to simplify the presentation of the lecture topic so that students could follow the lecture instruction within one file without needing to navigate to multiple alternate files.  

While not it is not a technical limitation to separate HTML, CSS and JS. It is always a good practice to follow.  Other developers would expect it and it helps with code maintenance (ie knowing where to look for specific code sources).

With regards to your question:

**Javascript** 
JavaScript code is inserted between `<script>` and `</script>` tags.
Scripts can be placed in the `<body>`, or in the `<head>` section of an HTML page, or in both.
If the javascript source code is saved in a .js file it is considered "externally referenced".

Reference:
[W3 Schools | Javascript Where To](https://www.w3schools.com/js/js_whereto.asp)

**CSS**
There are three ways to insert CSS: external, internal, inline.

Reference:
[W3 Schools | How To Add CSS](https://www.w3schools.com/css/css_howto.asp)

**Comment by katz2row** [comment]
It seems to me that:

- External - script tag referencing an external file
- Internal - script tag with JS code within the opening and closing tags in the HTML document
- Inline - JavaScript within the HTML node; for instance within the v-for=" " quotes

All that said, I could not for the life of me find anything that actually distinguished between internal and inline in my Google searches. So I am not sure if this assumption is correct, but during the lectures this is what I interpreted from what was said.

**Comment by susanBuck** [comment]
Closing this thread, but feel free to re-open if there are any follow-up questions.
