### ISSUE TITLE
Binding Quirks

### ISSUE THREAD

**Issue by jaredmimms** [susanBuck/e28-spring21#17]
```
const ShoppingList = {
    data() {
        return {
            item: {

            },
            itemList: [],
            qty: 0
        }
    },
    methods: {
        addItem() {
            this.itemList.push(this.item);
            this.qty += this.item.qty;
            this.item = {};
        },
        deleteItem(index) {
            this.qty -= this.itemList[index].qty;
            this.itemList.splice(index, 1);
        }
    }
}
const app = Vue.createApp(ShoppingList).mount('#app');
```

I noticed on my shopping list application that the item bound to the input fields by model even after pushed into the `itemList` array. I saw the video for this week talk about this issue. I wonder why setting `this.item = {};` after pushing the item into the array solved the binding problem.

**Comment by acomjean** [comment]
I think its a two-way binding, so setting a value in the method binds it back to the form.   (I think this is what you are asking) 

Note that when you push a string or number onto an array javascript adds a new copy of that string or number. 
but when you push a array or an object onto the array its added by reference (so changes to the initial variable show up in the thing you pushed onto the array.

This might explain it better.

https://stackoverflow.com/questions/8660901/do-objects-pushed-into-an-array-in-javascript-deep-or-shallow-copy

**Comment by susanBuck** [comment]
Interesting observation, @jaredmimms.

It appears that setting the item to a empty object "breaks" the reactivity of it. If we just update it in some other way, for example - updating the properties - the reactivity still applies, e.g.:

```js
   addItem() {

            this.items.push(this.item);
            this.itemsCount += this.item.qty;

            // This would cause the item we just added to the items array to reactively update:
            //this.item.name = 'foo';
            //this.item.qty = 5;

            // This would not
            this.item = {}

        },
```

Going to do some investigating into why this is and will report back with what I find.

**Comment by susanBuck** [comment]
Had a moment to dig further into this and I think I've narrowed down why this is happening...

I'm assuming based on the code you shared that your inputs look something like this:

```html
<input id='qty' type='text' v-model='item.qty'>
<input id='name' type='text' v-model='item.name'>
```

Note that we're modeling data after specific properties of our object, _item.qty_ and _item.name_.

Here's what I suspect is happening:

Upon adding a new item, we add the _item_ to _items_:

```js
this.items.push(this.item);
```

Then, we reset _this.item_ to an empty object...

```js
this.item = {}
```

**...when we do this we're effectively deleting the properties _item.name_ and _item.qty_.** You can observe this in the Vue dev tools - right before we add an item, we see _item.name_ and _item.qty_:

![image](https://user-images.githubusercontent.com/237711/109747094-891a7e80-7ba4-11eb-808f-a3c786fbafc2.png)

But once we add the item, those properties no longer exist:

![image](https://user-images.githubusercontent.com/237711/109747141-9c2d4e80-7ba4-11eb-932e-5af90c9191fd.png)


**Then, when we enter values for a new item again, the v-model on the inputs cause the properties _item.name_ and _item.qty_ to be recreated as new instances of reactive data, thus not impacting the previous instances of this data we had already added to items:**

![image](https://user-images.githubusercontent.com/237711/109747457-25dd1c00-7ba5-11eb-94c4-2b14e7759332.png)


As further evidence of this, if we were to reset our item doing something like this:

```js
this.item.name = null;
this.item.qty = null;
```

It *would* retain the reactivity, updating each existing item in the list, because the properties _name_ and _qty_ are never deleted, and thus they're never recreated as new reactive data.

This is my current hypothesis as to what's going on - but I'll revisit this in the morning with a fresh set of eyes to see if I see something different. : )

**Comment by agt25** [comment]
Great question @jaredmimms! Loved @susanBuck's detailed response. I do not have any input, so my apologies if this reply is not allowed! I'll add that I like how natural the 'this' keyword is but it also boggles my mind at times. Really hoping I'm not the only one who feels that way! :sweat_smile:

**Comment by susanBuck** [comment]
I don't think you're alone on the `this` keyword @agt25 : )

I've always found it challenging to teach because it's just such a abstract word to have to talk about - *this* - it's a weird/nebulous term.

**Comment by susanBuck** [comment]
Closing this post due to inactivity, but feel free to continue the discussion or post a new thread if any questions are still pending.
