### ISSUE TITLE
Assignment for Week 6 Repeat Question

### ISSUE THREAD

**Issue by jaredmimms** [susanBuck/e28-spring21#19]
In the assignment for week 6 question preview I see two of the same question - 6 and 9. 

Both questions read: 

In lecture, we saw how a component's template could be defined within our HTML file in a <script type='text/xtemplate'> element.
What is a downside of this approach?

Is this by design? Is it different in the actual assignment from the preview? What should I do about this?

**Comment by susanBuck** [comment]
Hi @jaredmimms -

It's not by design - not sure how it got in there twice. Apologies for any confusion!

Because some students have already completed the assignment, I'll just leave it there - so go ahead and answer the same for both questions. If a student misses this question, I'll make sure they only get the deduction once.
