### ISSUE TITLE
Managing two git repositories, ssh keys when taking two classes at same time

### ISSUE THREAD

**Issue by kerynegan** [susanBuck/e28-spring21#2]
Hi Susan,

I've decided to take both CSCI E-15 and DGMD E-28 simulaneously this term, and I'm wondering about managing the various project files appropriately from the beginning. 

- Is there any reason to set up two separate ssh keys for Github? My instinct is no, but I'm not sure if - in a real world application - would there be security concerns for having them be the same? If so, how do I go about switching between them in command line? 
- My initial plan is to have two separate folders inside my XAMPP/htdocs, one each for E28 and E15, and each of those cloned to the appropriate repository in Github using git clone command. Does that make sense? 
- If so, my git add/git commit commands would only commit those items that have changed from the folder I am in, right? That is, to add/commit changes for E28 and not E15, I would simply make sure that I was inside the E28 folder, not the parent htdocs folder? 
- During the course, do you expect there will be any changes I might be making to the parent folders that may affect the other course that I should keep an eye out for?
- Are there any other considerations you think I should keep in mind?

I'm sure I may have more questions as we get to the production server setup, but I wanted to ask these things before I set up my second repository correctly this week. I have set up E28 so far. 

I've used Github and command lines before in CSCI E-31 (Node.js) but I've never had a reason to be working in multiple projects at once before. I'm using a Mac/Terminal. 

Thanks!
Keryn

**Comment by susanBuck** [comment]
Great questions, @kerynegan!

No need for separate keys for the two different courses. You are correct, though, in thinking it would be wise to use different keys in the real world, especially if the keys were for connecting to servers that are part of apps/companies that are unrelated. This way, should one of the keys become compromised, it would only impact the one app/company. 

Yes, you are correct - two separate repos/directories, one for each course. 

The only thing to be on the look out for when it comes to managing the two different courses will come into play when we set up local and production domains, just making sure you don't use the same subdomains for the different courses. This shouldn't be a problem when it comes to projects, because the instructions I'll give you have you prefix the project with the course number (e.g. `e28-p1.yourdomain.loc`), so that'll make it unique.

I can't think of any other complications - I actually run the same setup each semester as I typically teach two separate courses a semester.

Don't hesitate to let me know if you have any other questions as you dig further into it.

**Comment by sgreene** [comment]
This doesn't apply to your situation, but I thought I'd share my slightly different git setup just in case anyone is in a similar situation.  I have to use two different git remote servers. One is for github.com and the other is my company's internal git server (which is actually based on a competing product called gitlab).  Obviously my company expects me to keep the two things separate and so I've taken the following steps:

* I have separate ssh keys and configured the right key to be automatically used based on the domain name of the server. I basically followed these steps to do that: https://code.tutsplus.com/tutorials/quick-tip-how-to-work-with-github-and-multiple-accounts--net-22574 (step 3)
* Git stores things like your username and email address in `~/.gitconfig` . To avoid constantly changing my personal email address to work email address and vice versa when pushing to a repo, I use completely separate root folders for work and non-work projects (a good idea anyway). Here's a SO answer that's closest to what I do https://stackoverflow.com/questions/4220416/can-i-specify-multiple-users-for-myself-in-gitconfig/43654115#43654115

**Comment by susanBuck** [comment]
Thanks for adding these resources, @sgreene! You touched on the part I missed in @kerynegan's original question which is how to to force SSH to use a specific key for a specific server.

For reference, here's another good resource that expounds on what you can do in the SSH config file: https://linuxize.com/post/using-the-ssh-config-file

**Comment by jaredmimms** [comment]
I use the same SSH key for two classes. I remember running a production server when I could not afford to compromise security that way. I try to set up different security keys and passwords for different sites. I get a warning in Chrome when my passwords become compromised. I don't exactly know how this works.

**Comment by susanBuck** [comment]
@jaredmimms I believe Google/Chrome monitors known password/security breaches on sites, and if it you have a password stored in Chrome for one of those sites, it lets you know. [More details here...](https://support.google.com/accounts/answer/9457609?p=saved-pw-checkup&hl=en&visit_id=637485691933518529-2147513236&rd=1#)

I'm going to close out this thread as I believe @kerynegan's original questions have been addressed, but don't hesitate to re-open or start a new thread if anyone has any follow-up questions.
