### ISSUE TITLE
Recomputing computed property, or otherwise moving to next random item

### ISSUE THREAD

**Issue by kerynegan** [susanBuck/e28-spring21#29]
**Repository URL**
[P2 Github repository](https://github.com/kerynegan/e28/tree/main/p2)
[API Github repository](https://github.com/kerynegan/e28/tree/main/e28api)

**Production URL**
[P2 production link](http://e28p2.kerynegan.me/)
[API production link](http://e28api.kerynegan.me/)

**Describe the problem**
I have a movies page (@/components/pages/MoviesPage.vue) that ideally will load one random movie at time (@/components/ShowMovie.vue) for a user to select whether or not they are interested in that movie. 

The random movie is first generated with a computed movie() property on the MoviesPage to filter the movies pulled in  from the API.

Once the user selects yes, the event is passed from ShowMovie to MoviesPage to the RootVue, which then pushes the User's ID (which can be chosen via buttons at the top of the page for now) and the Movie's ID to a selections table on the API. 

Right now, the RootVue then reloads the movies (via loadMovies()), but I would rather find a way to recalculate the computed movies() property, so that I'm not reloading everything but simply going to the next random movie in the batch. 

But I think I'm a bit out of my depth - it seems from error alerts that computed properties should not be changed directly via a method (though maybe they can be updated by a change to a value that the property depends on? I'm not clear about the reactivity there). So far, I've tried a few combinations of moving it to methods, adding the call as something like v-on:nextMovie, etc., but can't seem to get it to work correctly. 

Note for anyone looking at this, if you get stuck on the /movies page at any point with a Loading message, try refreshing a few times, or going to Home and back to Movies. Hopefully this fix will solve that. 

Also, if you're poking around, the other pages (meals, drinks, matches) are still very much in-progress, but should eventually work similarly.

**Comment by susanBuck** [comment]
I suggest converting your `movie` computed property (the one that gets a random movie) to a method. Let's call it `updateMovie`.

Within this method, it should set/update a data property, `movie`.

This method should get invoked at two points:

1. Via a watcher of `movies`, forcing it to be invoked initially once the movies are loaded
2. Within the existing _selectMovie_ method so it'll be invoked again whenever the user chooses "Yes"

For reference, here's the code I wrote to test that above solution would work as expected: https://gist.github.com/susanBuck/60e926c6f940542b956440939ae6161a

---

FYI I believe sometimes your movies were occasionally failing to load because the _"Choose a random movie"_ logic had the potential to not pick a movie.

Here's what the code was:
```js
this.movie = this.movies.filter((movie) => {
    return (movie.id == Math.floor(Math.random() * this.movies.length));
}, this.id)[0];
```

This code says: _Loop through all the movies, and filter out just the movie that matches some random number._
The problem is, a different random number is generated each iteration of the filter. Because of this, there's the potential for it to filter through and never get a match.

To fix, pick the random number _before_ the filtering:

```js
let randomNumber = Math.floor(Math.random() * this.movies.length);
this.movie = this.movies.filter((movie) => {
    return movie.id == randomNumber;
}, this.id)[0];
```

Or, even better - rather than having to filter/iterate through each movie, just use the random number as an index to extract a movie from the array:

```js
let randomNumber = Math.floor(Math.random() * this.movies.length);
this.movie = this.movies[randomNumber];
```

---

Let me know if you have any questions about the above. On a side note, your code is very neat & organized - made it easy to jump into the problem and logic through what you were aiming for. 👍

**Comment by susanBuck** [comment]
I forgot to add: With my above suggestion, you should no longer invoke `this.loadMovies();` within the `selectMovie` method in App.vue.

**Comment by kerynegan** [comment]
Thank you very much!! I think I had all these pieces at various points yesterday, but just could not seem to get them to work right together (including that randomNumber re-work at one point). 

I've fixed my code and it's working great both in local and production 🙂
