### ISSUE TITLE
Refresh data from API after post new item

### ISSUE THREAD

**Issue by richiecarey** [susanBuck/e28-spring21#31]
Before I post links to the site, repo, etc I was hoping to ask a more general question to point me in the right direction ...

I'm able to post a new item to the API successfully via a `NewTask.vue` component with this function:

```js
    addTask() {
      axios.post("/task", this.newTask).then((response) => {
        if (response.data.errors) {
          this.errors = response.data.errors;
          this.showConfirmation = false;
        } else {
          this.$emit("update-tasks");
          this.showConfirmation = true;
        }
      console.log(this.showConfirmation);
      });
```

The item will load from the API if I hard refresh the page so I know it's there (in addition to the affirmative response from the API after the post)

However, I'm unsure of the correct way to trigger a re-render of the newly updated list of items (i.e. a fresh result set from the API) 

After quite a bit of time and trail and error I'm having no luck with `this.$emit("update-tasks")` triggering `loadTasks()` in App.vue .. or anywhere .. seems like `this.$emit("update-tasks")` isn't firing at all .. 

I'm wondering if I missed something and maybe that isn't even the correct approach to re-render after adding posting / adding a new item to the API? 

Thanks in advance!

**Comment by susanBuck** [comment]
It's the right approach (or at least one right approach). It's how we handled updating the product list after a new product was added. 

Is the p2 code you have in Github the latest? I can clone on my end to help you debug why `this.$emit("update-tasks")` is appearing not to fire.

**Comment by richiecarey** [comment]
Hi Susan,

I've updated the repo and prod servers with the latest code .. thanks!

---

**Repository URL**
https://github.com/richiecarey/e28/tree/main/p2

**Production URL**
http://e28p2.richiecarey.com/

**Describe the problem**
Task list does not re-render after post new item, seems to re-render after checking checkbox for 'done'

**Comment by susanBuck** [comment]
Great - taking a look now! Will report back shortly.

**Comment by susanBuck** [comment]
Narrowed down the issue -

Your component structure is: _App > ToDo > AddTask_

In _AddTask_ you were trying to trigger an event up to _App_, but **events only trigger up one level from child to parent**. 

Thus, you can't go from _AddTask_ to _App_.

A quick way to address this is to listen for the event in _ToDo_, and then have it trigger the event to _App_. So _AddTask_ communicates to _ToDo_ which communicates to _App_.

This feels a little clunky, because it is. :-) This actually is a good example of where things can get messy when it comes to managing data communication amongst multiple components, and is something we'll talk about this week when we talk about state management.

I suggest implementing the above solution for a "quick fix" and then refactoring after watching this week's material.

**Comment by richiecarey** [comment]
Excellent .. I was starting to suspect it was something like that ... will work on this again tonight after work .. thanks!

**Comment by susanBuck** [comment]
Sounds good! Going to go ahead and close this issue out, but if it's still giving you problems after working on it, just re-open the thread. : )
