### ISSUE TITLE
Error: Maximum recursive updates exceeded. 

### ISSUE THREAD

**Issue by kerynegan** [susanBuck/e28-spring21#41]
**Repository URL**
[https://github.com/kerynegan/e28/tree/main/p3](https://github.com/kerynegan/e28/tree/main/p3)

**Production URL**
Loading of the selections page fails because of the recursive problem, but:
[http://e28p3.kerynegan.me/](http://e28p3.kerynegan.me/).

**Describe the problem**
I'm getting a recursive data error on my display my selections page.

> Uncaught (in promise) Error: Maximum recursive updates exceeded. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

I know that something is being called over and over again, but I can't seem to nail down what exactly it is.

**To Reproduce**
1. Click on the "Account" Page
2. Log in as jill@harvard.edu, password: asdfasdf
3. Click on the link to "View my Selections."
4. In production, the page won't load the selections - it gets stuck in the error and never loads/times out. In my local file, the page will load the selections, but the error is in the console.

**Comment by susanBuck** [comment]
I was able to narrow down the issue to the methods that generate the movie, meal, and drink URLs.

To narrow it down, I first put a console.log in every method/computed property/watcher to see if I could see which one was being invoked excessively. 

This didn't turn up any suspects, so next I started commenting out parts of the template until I could narrow down what parts of the template were causing the recursive error to show. This narrowed things down to the part of the code invoking the _movieURL_, _mealURL_, and _drinkURL_ methods.

I noticed each of these methods was updating the same data property, _url_. However, the data property wasn't really being used - it was just a value returned from the methods. Given this, I decided to remove the data property URL from the equation  so instead of the URL methods looking like this:

```js
movieURL(x) {
    this.url = "/movies/" + x;
    return this.url;
}
```

They now looked like this:
```
movieURL(x) {
    return "/movies/" + x;            
}
```

**With this change to all 3 url methods, the recursive problem went away.**

I think this is more logical for a couple reasons:

1. You shouldn't need to return data properties. The nature of data properties is they are reactive - so when they change, they automatically update wherever they're being used. You shouldn't need to explicitly return them.
2. I think it's a little confusing to use one single data property (url) for three different things (movie url, meal url, drink url)

That being said, I still haven't put my finger on _why_ this was causing a recursion issue. If your URL methods were computed properties - that would make sense - computed properties look at their dependent data and are automatically invoked whenever that dependent data is updated. So in this case, if you had three computed properties relying on the url data property and were being invoked whenever the url was being updated, this would cause an infinite loop.

But your URL methods were just regular methods, not computed properties.

I need to revisit the "why" of this at a later point, but I did want to post this solution now so you could move forward.

**Comment by kerynegan** [comment]
This fix worked perfectly! Thanks very much! 

If you figure out why it was causing the issue, I'd be interested to know! It stumped me for a few hours before I gave up and asked for help, haha.

Thanks again!
